### PR TITLE
Fix the persistence of cropped photos on AWS

### LINKED ISSUE #30: After cropping the uncropped image is persisted to AWS
Will fix this weekend!

@michaeldejong

### PR DESCRIPTION
**Pull request by rogierslag**
Closes #30 

@michaeldejong @inventid/tech Ready for review!

I've extracted the cropping to a simple `if` stuff, which is then persisted to AWS

### CODE REVIEW

**Comment by michaeldejong** [comment]
:+1:

File: resize.js [hunk 1]
```diff
@@ -220,73 +220,72 @@ image.encodeAndUpload = function (fileName, fileType, resolutionX, resolutionY,
...
+          cropHeight = size.height / resizeFactor;
+          cropY = (cropHeight - resolutionY) / 2;
         }
+      }
+
+      var workImageClient = gm(file)
+        .options({imageMagick: true})
+        .autoOrient();
+
+      if (resizeFactor) {
```
Comment (michaeldejong) [inline resize.js]: Might be nicer to check if `cropX` etc is set (or put that in an object of its own).
